src/traffic_app_flask/models.py
from sqlalchemy import Integer, String
from sqlalchemy.orm import Mapped, mapped_column
from . import db


class User(db.Model):
    id: Mapped[int] = mapped_column(primary_key=True)
    username: Mapped[str] = mapped_column(unique=True)
    email: Mapped[str]


class Borough(db.Model):
    __tablename__ = "boroughs"
    borough_id: Mapped[int] = mapped_column(
        Integer, primary_key=True, autoincrement=True
    )
    la_code: Mapped[str] = mapped_column(String(10), nullable=False)
    borough_name: Mapped[str] = mapped_column(String(50), nullable=False)

    def __str__(self):
        return self.borough_name


class TrafficFlow(db.Model):
    __tablename__ = "traffic_flows"
    flow_id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    borough_id: Mapped[int] = mapped_column(
        Integer, db.ForeignKey("boroughs.borough_id")
    )
    year: Mapped[int] = mapped_column(Integer, nullable=False)
    cars: Mapped[float] = mapped_column(db.Float, nullable=False)
    all_vehicles: Mapped[float] = mapped_column(db.Float, nullable=False)


borough = db.relationship("Borough", backref=db.backref("traffic_flows", lazy=True))

src/traffic_app_flask/__init__.py
import os
from flask import Flask
from .dash_app.dashboard import init_dash
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy.orm import DeclarativeBase
from pathlib import Path


class Base(DeclarativeBase):
    pass


db = SQLAlchemy(model_class=Base)


def create_app(test_config=None):
    # create and configure the app
    app = Flask(__name__, instance_relative_config=True)
    # specify the location of the database, which is in the database folder and not in the instance folder
    trafficdb_location = Path(__file__).parent.joinpath("database", "traffic.db")
    app.config.from_mapping(
        SECRET_KEY="dev",
        # SQLALCHEMY_DATABASE_URI = "sqlite:///C:\\Users\\uswe\\OneDrive - University College London\\Desktop\\COMP0034 T2 2025\\comp0034-cw2-zcemys1\\src\\instance\\traffic.db",
        # SQLALCHEMY_DATABASE_URI = "sqlite:///../src/instance/traffic.db",
        SQLALCHEMY_DATABASE_URI="sqlite:///" + str(trafficdb_location),
        SQLALCHEMY_TRACK_MODIFICATIONS=False,
        SQLALCHEMY_ECHO=True,
    )

    if test_config is not None:
        # load the instance config, if it exists, when not testing
        app.config.from_mapping(test_config)

    # ensure the instance folder exists
    try:
        os.makedirs(app.instance_path)
    except OSError:
        pass

    db.init_app(app)

    with app.app_context():

        db.create_all()
        # pass

    # import routes from starter
    from . import routes

    app.register_blueprint(routes.bp)

    init_dash(app)

    # Add the shutdown function here to clean up sessions after each request
    # @app.teardown_appcontext
    # def shutdown_session(exception=None):
    #   db.session.remove()

    return app


# flask --app src.traffic_app_flask run --debug

src/traffic_app_flask/routes.py
from flask import Blueprint, render_template, request
from .form import BoroughFlowForm, TrafficDataRequestForm
from .models import TrafficFlow, Borough
import pandas as pd

# from src.traffic_app_flask import db wasnt letting tests pass
# from traffic_app_flask import db wasnt letting flask run
from . import db  # this then worked for both


bp = Blueprint("bp", __name__)


@bp.route("/")
def index():
    return render_template("index.html", message="Hello, Flask!")


# This is for dash app


@bp.route("/dashboard")
def dashboard():
    return render_template("dashboard.html", dash_url="/dash_app/")


# This is for the ulez check page


@bp.route("/ulez_check/", methods=["GET", "POST"])
def ulez_check():
    result = None

    if request.method == "POST":
        fuel_type = request.form.get("fuel_type")
        year = int(request.form.get("year"))

        if fuel_type == "Petrol" and year <= 2005:
            result = "Your vehicle is NOT ULEZ compliant."
        elif fuel_type == "Diesel" and year <= 2014:
            result = "Your vehicle is NOT ULEZ compliant."
        else:
            result = "Your vehicle is ULEZ compliant."

    return render_template("ulezcheck.html", result=result)


# THIS IS FOR TRAFFIC FLOW VIEWING FORM
@bp.route("/flow/", methods=["GET", "POST"])
def flow():
    form = BoroughFlowForm()
    traffic_data = None
    historic_result = None
    borough = None
    try:
        # latest results:
        if form.validate_on_submit():
            borough = form.borough.data

            traffic_data = (
                TrafficFlow.query.filter_by(borough_id=borough.borough_id)
                .order_by(TrafficFlow.year.desc())
                .first()
            )

        # second form:
        elif request.method == "POST" and "historic_submit" in request.form:
            year = int(request.form.get("year"))
            vehicle_type = request.form.get("vehicle_type")
            borough_id_str = request.form.get("borough_id")
            if borough_id_str:
                borough_id = int(borough_id_str)
            else:
                borough_id = None

            borough = db.session.get(Borough, borough_id)

            # borough = Borough.query.get(borough_id)
            record = TrafficFlow.query.filter_by(
                borough_id=borough_id, year=year
            ).first()

            historic_result = {
                "year": year,
                "vehicle_type": vehicle_type,
                "value": getattr(record, vehicle_type) if record else None,
            }

            traffic_data = (
                TrafficFlow.query.filter_by(borough_id=borough_id)
                .order_by(TrafficFlow.year.desc())
                .first()
            )

        return render_template(
            "boroughtraffic.html",
            form=form,
            borough=borough,
            traffic_data=traffic_data,
            historic_result=historic_result,
        )
    finally:
        # Close the session to avoid any potential issues
        db.session.close()


# this is for traffic data request page


@bp.route("/data_request/", methods=["GET", "POST"])
def data_request():
    form = TrafficDataRequestForm()

    if form.validate_on_submit():
        borough_id = form.borough.data
        year = form.year.data

        borough_id = borough_id.borough_id

        # Query traffic data based on the selected borough_id and year
        traffic_data = TrafficFlow.query.filter_by(
            borough_id=borough_id, year=year
        ).all()
        print("++++++++++", traffic_data[0].borough_id)

        write_data = []
        for data in traffic_data:
            temp = {
                "year": data.year,
                "borough_name": Borough.query.get(data.borough_id).borough_name,
                "cars": data.cars,
                "all_vehicles": data.all_vehicles,
            }
            write_data.append(temp)
        print("write_data:", write_data)

        data_save = pd.DataFrame(write_data)
        data_save.to_csv("traffic_data.csv", index=False)

    # NAME THE FILE ON THE COURSEWORK THE EXPORT ONE SO SARAH DOESNT GET CONFUSED
    # # Create a CSV file from the traffic data using BytesIO
    # output = StringIO()
    # writer = csv.writer(output, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)

    # # Write the header row
    # writer.writerow(['Borough', 'Year', 'Vehicle Type', 'Traffic Flow'])

    # for record in traffic_data:
    #     borough_name = record.borough_id  # Get the borough name
    #     # Normalize vehicle_type to match database column names
    #     vehicle_type_column = vehicle_type.lower()
    #     writer.writerow([borough_name, record.year, vehicle_type, getattr(record, vehicle_type_column, "N/A")])

    # # Send the CSV file as an attachment
    # return send_file(output, mimetype='text/csv', download_name='traffic_data.csv', as_attachment=True)

    return render_template("data_request.html", form=form)

src/traffic_app_flask/templates/base.html
<!doctype html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}Traffic Analysis{% endblock %}</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="{{ url_for('static', filename='custom.css') }}">



</head>

<body>

  {% if request.endpoint != 'bp.index' %}
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary"> <!--this is for the navigation bar-->
    <a class="navbar-brand" href="/">ULEZ Analysis</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/dash_app/">What is ULEZ?</a> <!--THIS IS THE LINK TO THE DASH APP-->
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/data_request/">Traffic Data Request</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/ulez_check/">Check Vehicle</a> <!--THIS is syntax for page routes-->
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/flow/">Check Traffic Status</a>
        </li>

      </ul>
    </div>
  </nav>

  {% endif %}
  <div class="container mt-4">
    {% block content %}{% endblock %}
  </div>

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>


</body>

</html>

src/traffic_app_flask/templates/boroughtraffic.html
{% extends "base.html" %}

{% block title %} Check Borough Traffic {% endblock title %}


{% block content %}

<h1 style="text-align:center;">Check the traffic status of a borough</h1>

<form method="POST" action="/flow/">
    {{ form.csrf_token }}
    {{ form.borough.label }} 
    {{ form.borough(class_="form-control") }}
    <input type="submit" value="Go" class="btn btn-primary mt-2">
</form>

<div id="flow-latest" class="mt-4"><br> 
    {% if borough %}
        <p class="text-bg-info p-2">Traffic flow data for: <strong>{{ borough.borough_name }}</strong></p>
    {% endif %}
</div>


{% if traffic_data %}
    <table class="table table-bordered mt-3">
        <thead>
            <tr>
                <th>Year</th>
                <th>Cars</th>
                <th>All Vehicles</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ traffic_data.year }}</td>
                <td>{{ traffic_data.cars }} million vehicle kilometres</td>
                <td>{{ traffic_data.all_vehicles }} million vehicle kilometres</td>
            </tr>
        </tbody>
    </table>

{% elif borough %}
    <p class="mt-3">No traffic data found for {{ borough.borough_name }}.</p>
{% endif %}



<hr class="my-4">
<h4>Want to look back in time for your borough?</h4>

<form method="POST" action="/flow/">
    {{ form.csrf_token }}

    <div class="mb-3">
        <label for="year">Select a year:</label>
        <select name="year" class="form-select" required>
            {% for y in range(1993, 2024) %}
            <option value="{{ y }}">{{ y }}</option>
            {% endfor %}
        </select>
    </div>

    <div class="mb-3">
        <label>Select vehicle type:</label><br>
        <input type="radio" name="vehicle_type" value="cars" required> Cars<br>
        <input type="radio" name="vehicle_type" value="all_vehicles"> All Vehicles
    </div>

    <input type="hidden" name="borough_id" value="{{ borough.borough_id }}">
    <button type="submit" name="historic_submit" value="1" class="btn btn-secondary">Submit</button>
</form>


{% if historic_result %}
    <div id="flow-historical"class="mt-4">
        <h5>Historic Traffic Data</h5>
        {% if historic_result.value %}
            <p>
                In {{ historic_result.year }}, 
                there were <strong>{{ historic_result.value }}  million vehicle kilometres</strong> 
                {{ historic_result.vehicle_type.replace('_', ' ') }} in 
                {{ borough.borough_name }}.
            </p>
        {% else %}
            <p>No data found for {{ historic_result.year }} in {{ borough.borough_name }}.</p>
        {% endif %}
    </div>
{% endif %}


    <a href="/">Go back to the homepage</a>
{% endblock content %}

src/traffic_app_flask/templates/dashboard.html
{% extends "base.html" %}

{% block title %} Dashboard 1 {% endblock title %}


{% block content %}

<iframe noresize='noresize' style='position: absolute; background: transparent; width: 95%; height:100%;' src={{
    dash_url }} frameborder="0">
</iframe>



{% endblock content %}

src/traffic_app_flask/templates/data_request.html
{% extends "base.html" %}

{% block content %}
<h1>Traffic Data Request</h1>
<p style="font-size:160%;">Want to try work with your personalised traffic flow data? Enter your preferences below:</p>

<form method="POST" action="/data_request/">
    {{ form.csrf_token }}

    <div class="form-group">
        {{ form.borough.label }}
        {{ form.borough(class_="form-control") }}
    </div>

    <div class="form-group">
        {{ form.year.label }}
        {{ form.year(class_="form-control") }}
    </div>

    <div class="form-group">
        {{ form.vehicle_type.label }}
        {{ form.vehicle_type(class_="form-control") }}
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% if traffic_data %}
<h3 class="mt-4">Requested Traffic Data</h3>
<table class="table table-bordered mt-4">
    <thead>
        <tr>
            <th>Year</th>
            <th>Cars</th>
            <th>All Vehicles</th>
        </tr>
    </thead>
    <tbody>
        {% for record in traffic_data %}
        <tr>
            <td>{{ record.year }}</td>
            <td>{{ record.cars }} million vehicle kilometres</td>
            <td>{{ record.all_vehicles }} million vehicle kilometres</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% elif form.is_submitted() %}

{% endif %}

<a href="/">Go back to the homepage</a>
{% endblock %}

src/traffic_app_flask/templates/index.html
{% extends "base.html" %}

{% block title %} Dashboard 1 {% endblock title %}


{% block content %}


<style>
    body {
        background-color: #eef7ff;
        /* Light blue background */
    }

    p {
        border: 10px solid powderblue;
        margin: 100px;
    }
</style>


<h1 style="text-align:center;"><abbr title="Ultra Low Emission Zone">ULEZ</abbr> Analysis</h1>
<hr>
<h3>

    <style>
        h3 {
            text-align: center;
            color: #0016dd;
            /* Blue */
        }
    </style>
    Where are you trying to go?
</h3>

<p><a href="/dash_app/" class="btn btn-info btn-lg d-block">Find out more about how traffic has affected people</a></p>



<p><a href="{{ url_for('bp.ulez_check') }}" class="btn btn-info btn-lg d-block">Check your vehicle</a></p>
<p><a href="{{ url_for('bp.flow') }}" class="btn btn-info btn-lg d-block">Traffic Status</a></p>
<p><a href="{{ url_for('bp.data_request') }}" class="btn btn-info btn-lg d-block">Data Request</a></p>
{% endblock content %}

src/traffic_app_flask/templates/login.html
{% extends "base.html" %}

{% block content %}
<h2>Sign In</h2>
<form method="post">
    {{ form.hidden_tag() }}
    <div class="mb-3">
        <p>
            {{ form.username.label }}<br>
            {{ form.username(class="form-control) }}
        </p>

        <p>
            {{ form.password.label }}<br>
            {{ form.password(class="form-control) }}
        </p>

        <p>{{ form.submit(class="btn btn-primary") }}</p>
</form>
{% endblock %}

src/traffic_app_flask/templates/ulezcheck.html
{% extends "base.html" %}

{% block title %} New Page {% endblock title %}

{% block content %}
<h1 class="text-center mt-4 mb-4 fw-bold">Check your vehicle compliancy</h1>


<iframe src="https://www.webuyanycar.com/free-car-check/emissions-check/" width="100%" height="500"
    title="Check your vehicle" class="mb-5"></iframe>


<h2 style="text-align:center;" class="mb-5">Choose your vehicle fuel type</h2>


<form action="/ulez_check" method="POST">
    <fieldset>
        <legend>Fuel Type:</legend>
        <input type="radio" id="petrol" name="fuel_type" value="Petrol" required>
        <label for="petrol">Petrol</label><br>

        <input type="radio" id="diesel" name="fuel_type" value="Diesel">
        <label for="diesel">Diesel</label><br>

        <input type="radio" id="electric" name="fuel_type" value="Electric">
        <label for="electric">Electric</label>
    </fieldset>


    <div class="mb-3">
        <label for="year">Vehicle Registration Year:</label>
        <select id="year" name="year" required>
            {% for y in range(1990, 2024) %}
            <option value="{{ y }}">{{ y }}</option>
            {% endfor %}
        </select>
    </div>
    <div class="mb-3">
        <input type="submit" class="btn btn-primary mt-3" value="Submit">
    </div>
</form>


{% if result %}
<h3>ULEZ Compliance Result:</h3>
<p>{{ result }}</p>
{% endif %}

<a href="/">Go back to the homepage</a>
{% endblock content %}